### ISSUE TITLE
No error handling

### ISSUE THREAD

**Issue by BhumikaShah39** [pranjalipudasaini/Farmish#6]
In registration page, when user tries to sign up without filling up values, no error handling messages is displayed

**Comment by pranjalipudasaini** [comment]
The bug has been fixed by adding user.save() inside a try-except block to catch any errors that may occur during user registration.
![Screenshot 2024-04-20 150705](https://github.com/pranjalipudasaini/Farmish/assets/119116985/b65a6a85-9249-4ef3-937d-3fe8a7031f3b)
